### ISSUE TITLE
Supplying 'bcs = None' to MechanicsProblem throws TypeError

### ISSUE THREAD

**Issue by alexdiem** [ComputationalPhysiology/pulse#1]
The constructor for MechanicsProblem explicitly uses 'bcs = None' to assign, default boundary conditions, however, when initiating MechanicsProblem on a HeartGeometry with 'bcs = None' line 160 in the MechanicsProblem constructor

`self.bcs_parameters.update(**bcs_parameters)`

throws a TypeError:

`TypeError: update() argument after ** must be a mapping, not NoneType`

**Comment by finsberg** [comment]
Fixed in #2
